version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - AWS_ACC=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f5)
      - REPOSITORY_URI=$AWS_ACC.dkr.ecr.$AWS_REGION.amazonaws.com
      - uname -a
      - java -version
  build:
    commands:
      - echo Build startedd on `date`
      - mvn package
      - docker build . -t $REPOSITORY_URI/${REPO}:latest
      - echo Build complete on `date`
  post_build:
    commands:
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 516394029386.dkr.ecr.us-west-2.amazonaws.com
      - aws ecr describe-repositories --registry-id ${AWS_ACC} --repository-name ${REPO}
      - docker push $REPOSITORY_URI/${REPO}:latest
      - echo {\"repo\":\"${REPO}\"} > repo.json
artifacts:
  files:
    - target/spring-petclinic-3.1.0.jar
    - repo.json